# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 271a6cec0ca0dd77418df28281ec23d933e8022662850f5c16c5d43c7a0aa1751e7e3eb940f5f8c5b29481092f78de446e4137ab71c932bdde50509037822bcb

test:
  secret_key_base: bb95c4913c9bd5febbfc78497a025a57f1a945fc0d6d7ab2d3f98b5721b437ea0d7d2353ca27fa1881dc7fc0cb44132c7209ecb1dfa36b845eca974fac5d2772

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
